awesome es6 refactoring
mrVanDalo/landingpage pull request #2
Opened 2017-03-17 13:46 UTC by jpkempf

got rid of jquery and bootstrap js, refactored code to native es6

2017-03-17 21:06 UTC, mrVanDalo requested changes
Would be great if you could do these small changes.

2017-03-17 21:06 UTC, mrVanDalo commented on docs/index.html
> +            text:"The only programming language that matters.",
hmm My intention here was not to rate languages. (Also it's wrong). please remove

2017-03-17 21:06 UTC, mrVanDalo commented on docs/index.html
> +        const title = `
would be nice if title would be optional like text

2017-03-17 21:06 UTC, mrVanDalo commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
not needed anymore

2017-03-17 21:20 UTC, jpkempf commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
how do you mean?

2017-03-17 21:21 UTC, jpkempf commented on docs/index.html
> +            text:"The only programming language that matters.",
just an innocent test string. sure, i can change it.

2017-03-17 21:22 UTC, jpkempf commented on docs/index.html
> +        const title = `
can do

2017-03-17 21:49 UTC, mrVanDalo commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
you dont use it anymore. there have to be a link now.

2017-03-17 22:34 UTC, jpkempf commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
sorry, still don't understand :[

2017-03-18 06:43 UTC, mrVanDalo commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
```            if (elem.image) { 
￼                 var image = elem.image;
￼             } else {
￼                 var image = content.defaultImage;
￼             }```
There was a default image before, but you don't use it anymore. That's ok, the `defaultImage` can to be removed now.

2017-03-20 08:15 UTC, jpkempf commented on docs/index.html
>          defaultImage: "http://i.giphy.com/l0HlRnAWXxn0MhKLK.gif",
ah. yeah, i wasn't sure if you still needed/wanted that for something. okay, gonna remove it.

2017-03-20 16:08 UTC, merged